spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${SERVER_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf-8
    username: ${DB_USER}
    password: ${DB_PASSWD}


  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_BUCKET}
